version: '3'

services:
    yt2mp3:
        build: .
        container_name: yt2mp3
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./docker-data/yt2mp3:/yt2mp3/docker-data
        environment:
            - "MINIO_URL=http://minio:9000/"
            - "MINIO_ACCESS_KEY=minio"
            - "MINIO_SECRET_KEY=password"
            - "MINIO_BUCKET=mp3"
            - "REDIS_HOST=redis"
            - "REDIS_PORT=6379"
            - "PORT=3000"
            - "KEY=xxxxxxx-xxxxxxxxxxxxxxxxxx"

    redis:
        image: redis:5.0.9
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - "./docker-data/redis:/data/"

    minio:
        image: minio/minio:RELEASE.2020-04-23T00-58-49Z
        container_name: minio
        restart: always
        ports:
            - 9000:9000
        volumes:
            - "./docker-data/minio:/data"
        environment:
            - "MINIO_ACCESS_KEY=minio"
            - "MINIO_SECRET_KEY=password"
        command: server /data